# -*- coding: utf-8 -*-
"""chat_Bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q1Z8gKbxf0Fs5n0Ve2I9k3M4y_0JW-p8
"""

!pip install langchain_huggingface

# from google.colab import userdata
# HF_TOKEN = userdata.get("HF_TOKEN")

from langgraph.graph import StateGraph, START, END
from typing import TypedDict, Annotated
from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
from langchain_core.messages import BaseMessage, HumanMessage
from langgraph.checkpoint.memory import MemorySaver

llm = HuggingFaceEndpoint(
    repo_id = "openai/gpt-oss-120b",
    huggingfacehub_api_token=HF_TOKEN,
    task = "text_generation"
)

model = ChatHuggingFace(llm=llm)

from langgraph.graph.message import add_messages
class ChatState(TypedDict):
  messages: Annotated[list[BaseMessage], add_messages]

def chat_node(state: ChatState):

  # Take user querry from state
  messages = state["messages"]

  # Send to llm
  response = model.invoke(messages)

  # Response store state
  return {"messages": [response]}

check_pointer = MemorySaver()

graph = StateGraph(ChatState)

graph.add_node("chat_node", chat_node)

graph.add_edge(START, "chat_node")
graph.add_edge("chat_node", END)

chat_bot = graph.compile(checkpointer=check_pointer)

initial_state = {
    "messages":[HumanMessage(content='What is the capital of Pakistan')]
}

response_model = chat_bot.invoke(initial_state)

response_model["messages"][-1].content

thread_id = "1"

while True:
  user_message = input("Type here...")
  print(f"User: {user_message}")
  if user_message.strip().lower() in ["exit", "bye", "quit"]:
    break

  config = {'configurable': {"thread_id": thread_id}}
  response = chat_bot.invoke({"messages":[HumanMessage(content=user_message)]}, config=config)

  print(f"AI : {response["messages"][-1].content}")

